{% set version = "0.2.0" %}

package:
  name: adjfind
  version: {{ version }}

source:
  url: https://github.com/zwang-geog/AdjFind/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 861fb40762edaafd9a014be4c306c3e47f7c7a2d6d90523b8d4cdc83c67e9ce1

build:
  number: 1
  script: |
    cmake -B build -S . ${CMAKE_ARGS}  # [unix]
    cmake -B build -S . %CMAKE_ARGS%  # [win]
    cmake --build build --config Release -j ${CPU_COUNT}  # [unix]
    cmake --build build --config Release -j %CPU_COUNT%  # [win]   
    cmake --install build

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - libgdal-core
    - libboost-devel

test:
  commands:
    - adjfind --help
    - adjfind --version

about:
  home: https://github.com/zwang-geog/AdjFind
  license: MIT
  license_file: LICENSE
  summary: CLI of specialized path finding algorithms related to adjacency/proximity
  description: |
    The command-line tool supports three main modes:
    • Road Segmentation Mode: Determines which service points (e.g., hydrants) are closest to each road segment using network distance, and optionally splits roads into discrete distance categories for service area analysis.
    • Neighboring Points Mode: Identifies the nearest neighboring service points along a road network in each direction, calculating spacing distances between facilities like hydrants for regulatory compliance assessment.
    • Structure Access Mode: Computes shortest unobstructed paths between building corners and road networks (e.g., assume fire engines can park anywhere along the provided road network) if road network is provided, or between building corners and access points (e.g., specific locations where fire engines can park) if road network is not provided. Moreover, it finds the least accessible points (a.k.a. furthest points) on buildings for emergency response planning and fire code compliance.
  doc_url: https://github.com/zwang-geog/AdjFind/blob/master/README.md
  dev_url: https://github.com/zwang-geog/AdjFind

extra:
  recipe-maintainers:
    - zwang-geog
